"""Add modules and persona metadata

Revision ID: 034b791674e6
Revises: d22b22e5a9f0
Create Date: 2026-03-31 23:21:24.023905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034b791674e6'
down_revision: Union[str, Sequence[str], None] = 'd22b22e5a9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('persona_modules',
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('persona_id', 'module_id')
    )
    op.add_column('personas', sa.Column('target_competencies', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('personas', sa.Column('estimated_duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'estimated_duration')
    op.drop_column('personas', 'difficulty')
    op.drop_column('personas', 'target_competencies')
    op.drop_table('persona_modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
